name: tf2.8
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cudnn=8.2.1
  - gdal=3.3.1
  - python=3.9.12
  - rasterio=1.2.6
  - pip:
    - geopandas==0.10.2
    - rio-tiler==3.1.4
    - shapely==1.6.4
    - tensorflow==2.8.0
    - tqdm==4.64.0
    - opencv-python==4.5.5.64
